[
  inputs: [
    "apps/*/{config,lib,priv,test}/**/*.{ex,exs}",
    "apps/*/mix.exs",
    "mix.exs",
    ".formatter.exs",
    ".iex.exs"
  ],
  locals_without_parens: [
    add: :*,
    arg: :*,
    belongs_to: :*,
    can: :*,
    config: :*,
    connection: :*,
    create: :*,
    description: :*,
    drop: :*,
    embeds_many: :*,
    embeds_one: :*,
    field: :*,
    forward: :*,
    fsm_fields: 1,
    gen_enum: :*,
    get: :*,
    has_many: :*,
    has_one: :*,
    import_fields: :*,
    import_types: :*,
    interface: :*,
    many_to_many: :*,
    middleware: :*,
    modify: :*,
    named: :*,
    object: :*,
    payload_object: :*,
    pipe_through: :*,
    plug: :*,
    policy: :*,
    reload: :*,
    remove: :*,
    render_error: :*,
    resolve_type: :*,
    resolve: :*,
    response: :*,
    serialize: :*,
    socket: :*,
    status: :*,
    store_named: :*,
    trigger: :*,
    types: :*,
    value: :*,
    whereis_name: :*,
    whereis: :*,
    set: :*
  ]
]
