name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: mix test
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '1.13.0'
          elixir-version: '25.0'
      - name: Install Dependencies
        run: mix deps.get
      - name: Run Tests
        run: mix test